### ISSUE TITLE
Vyzkoušet připojení přes Yellow credentials

### ISSUE THREAD

**Issue by Psychol0gicl** [RadekKaupe/ITE-Yellow-2024#2]
Vyzkoušet Yellow credentials na AWS (cvíko BSOI co jsme měli 7.10.). Pozor! Server může spát, pokud nebude fungovat napoprvé vyzkoušet podruhé po pěti minutách.

**Comment by RadekKaupe** [comment]
s

**Comment by Psychol0gicl** [comment]
22.10. vyzkoušeno a vše funguje. Musí se dělat dvakrát za sebou, prvním poštouchnutím se servery probudí, ale vrátí error code 504. Podruhé se stane to co má.
